// src/components/PlanPage/AddItemForm.jsx
import React, { useState, useEffect } from 'react';
import { supabase } from '../../supabaseClient';
// CSS handled by PlanPage.css (Shared Form Styles)

const AddItemForm = ({ onAddItem, onCancel, assignedPeopleForSingerRole, allAssignedPeople }) => {
  const [type, setType] = useState('Song');
  const [title, setTitle] = useState('');
  const [duration, setDuration] = useState('');
  const [details, setDetails] = useState('');

  // Song-specific state
  const [artist, setArtist] = useState('');
  const [chordChartUrl, setChordChartUrl] = useState('');
  const [youtubeUrl, setYoutubeUrl] = useState('');
  const [selectedSingerIds, setSelectedSingerIds] = useState([]); 

  // Bible Verse-specific state
  const [bibleBook, setBibleBook] = useState('');
  const [bibleChapter, setBibleChapter] = useState('');
  const [bibleVerseRange, setBibleVerseRange] = useState('');

  // Import Song Info State
  const [importMode, setImportMode] = useState('NONE'); 
  const [importedMusicianId, setImportedMusicianId] = useState(null);
  const [availableImportSongs, setAvailableImportSongs] = useState([]);
  const [loadingImportSongs, setLoadingImportSongs] = useState(false);

  useEffect(() => {
    setArtist(''); setChordChartUrl(''); setYoutubeUrl(''); setSelectedSingerIds([]);
    setBibleBook(''); setBibleChapter(''); setBibleVerseRange('');
    setImportMode('NONE');

    if (type === 'Divider') {
      setDuration('');
      setDetails('');
      setTitle(currentTitle => (currentTitle === '' || !['Song', 'Bible Verse', 'Generic', 'Divider'].includes(type) ? '---' : currentTitle));
    } else if (title === '---' && type !== 'Divider') {
      setTitle('');
    }
  }, [type]); 

  const handleSingerSelectionChange = (singerId) => {
    setSelectedSingerIds(prevSelectedIds =>
      prevSelectedIds.includes(singerId)
        ? prevSelectedIds.filter(id => id !== singerId)
        : [...prevSelectedIds, singerId]
    );
  };

  const handleStartImport = () => setImportMode('SELECT_MUSICIAN');

  const handleMusicianSelect = async (musicianId) => {
    setImportedMusicianId(musicianId);
    setLoadingImportSongs(true);
    setImportMode('SELECT_SONG');
    try {
        const { data, error } = await supabase.from('songs').select('*').eq('added_by_user_id', musicianId).eq('is_primary', false).order('title', { ascending: true });
        if (error) throw error;
        setAvailableImportSongs(data || []);
    } catch (err) {
        alert('Failed to fetch songs: ' + err.message);
        setImportMode('SELECT_MUSICIAN');
    } finally {
        setLoadingImportSongs(false);
    }
  };

  const handleSongImportSelect = (song) => {
      setTitle(song.title || '');
      setArtist(song.artist || '');
      setChordChartUrl(song.chord_chart_url || '');
      setYoutubeUrl(song.youtube_url || '');
      setImportMode('NONE');
      setAvailableImportSongs([]);
      setImportedMusicianId(null);
  };

  const handleCancelImport = () => {
      setImportMode('NONE'); setAvailableImportSongs([]); setImportedMusicianId(null);
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    let autoGeneratedTitle = title.trim();
    if (type === 'Bible Verse' && !autoGeneratedTitle && bibleBook.trim()) {
        autoGeneratedTitle = `${bibleBook.trim()} ${bibleChapter.trim()}:${bibleVerseRange.trim()}`;
    }

    if (type !== 'Divider' && type !== 'Bible Verse' && !autoGeneratedTitle) {
      alert('Please enter a title for the item.');
      return;
    }

    let newItemData = {
      type,
      title: type === 'Divider' ? (title.trim() || '---') : autoGeneratedTitle,
      duration: (type === 'Divider' || type === 'Bible Verse') ? null : (duration.trim() || null),
      details: (type === 'Divider' || type === 'Bible Verse') ? null : (details.trim() || null),
      artist: type === 'Song' ? (artist.trim() || null) : null,
      chord_chart_url: type === 'Song' ? (chordChartUrl.trim() || null) : null,
      youtube_url: type === 'Song' ? (youtubeUrl.trim() || null) : null,
      assigned_singer_ids: type === 'Song' ? selectedSingerIds : [], 
      bible_book: type === 'Bible Verse' ? bibleBook.trim() : null,
      bible_chapter: type === 'Bible Verse' ? bibleChapter.trim() : null,
      bible_verse_range: type === 'Bible Verse' ? bibleVerseRange.trim() : null,
    };

    onAddItem(newItemData);
    
    // Reset form
    setTitle(type === 'Divider' ? '---' : '');
    setDuration(''); setDetails('');
    setArtist(''); setChordChartUrl(''); setYoutubeUrl(''); setSelectedSingerIds([]);
    setBibleBook(''); setBibleChapter(''); setBibleVerseRange('');
  };

  const showTitleInput = type !== 'Divider';
  const showDurationAndDetails = type === 'Generic' || type === 'Song' || type === 'Bible Verse';

  // --- Render Import Views ---
  if (importMode === 'SELECT_MUSICIAN') {
      const uniqueMusicians = []; const map = new Map();
      if (allAssignedPeople) { allAssignedPeople.forEach(p => { if(!map.has(p.id)){ map.set(p.id, true); uniqueMusicians.push(p); } }); }

      return (
          <div className="glass-form import-view">
              <h3>Import Song Info</h3>
              <p className="form-group">Select a musician:</p>
              <div className="import-list">
                  {uniqueMusicians.length > 0 ? uniqueMusicians.map(m => (
                      <button key={m.id} type="button" className="import-list-item-btn" onClick={() => handleMusicianSelect(m.id)}>
                          {m.name} <span className="role-tag">({m.role})</span>
                      </button>
                  )) : <p>No musicians assigned.</p>}
              </div>
              <button type="button" className="cancel-btn" onClick={handleCancelImport} style={{marginTop: '15px', width: '100%'}}>Cancel</button>
          </div>
      );
  }

  if (importMode === 'SELECT_SONG') {
      return (
          <div className="glass-form import-view">
              <h3>Select a Song</h3>
              {loadingImportSongs ? <p>Loading...</p> : (
                  <div className="import-list">
                      {availableImportSongs.map(s => (
                          <button key={s.id} type="button" className="import-list-item-btn" onClick={() => handleSongImportSelect(s)}>
                              <strong>{s.title}</strong>
                              {s.artist && <span style={{display:'block', fontSize:'0.8em', color:'#64748b'}}>{s.artist}</span>}
                          </button>
                      ))}
                  </div>
              )}
               <button type="button" className="cancel-btn" onClick={() => setImportMode('SELECT_MUSICIAN')} style={{marginTop: '15px', width: '100%'}}>Back</button>
          </div>
      )
  }

  // --- Render Main Form ---
  return (
    <form onSubmit={handleSubmit} className="glass-form">
      <h3>Add New Service Item</h3>
      <div className="form-group">
        <label htmlFor="item-type">Type</label>
        <select id="item-type" value={type} onChange={(e) => setType(e.target.value)}>
          <option value="Generic">Service Item</option>
          <option value="Song">Song</option>
          <option value="Bible Verse">Bible Verse</option>
          <option value="Divider">Divider</option>
        </select>
      </div>

      {/* COMPACT ROW FOR SONG TITLE & ARTIST */}
      {type === 'Song' ? (
        <div className="form-group" style={{display:'grid', gridTemplateColumns:'1fr 1fr', gap:'1rem'}}>
           <div>
              <label htmlFor="item-title">Song Title</label>
              <input type="text" id="item-title" value={title} onChange={(e) => setTitle(e.target.value)} required />
           </div>
           <div>
              <label htmlFor="song-artist">Artist</label>
              <input type="text" id="song-artist" value={artist} onChange={(e) => setArtist(e.target.value)} placeholder="e.g., Hillsong" />
           </div>
        </div>
      ) : (
        showTitleInput && (
            <div className="form-group">
                <label htmlFor="item-title">{type === 'Bible Verse' ? 'Reading Title (optional)' : 'Title'}</label>
                <input type="text" id="item-title" value={title} onChange={(e) => setTitle(e.target.value)} required={type === 'Generic'} />
            </div>
        )
      )}

      {type === 'Divider' && (
         <div className="form-group">
            <label htmlFor="item-title">Divider Text (Optional)</label>
            <input type="text" id="item-title" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g., ---, Transition" />
        </div>
      )}

      {type === 'Song' && (
        <>
          {/* COMPACT ROW FOR LINKS */}
          <div className="form-group" style={{display:'grid', gridTemplateColumns:'1fr 1fr', gap:'1rem'}}>
             <div>
                <label htmlFor="song-chord-chart">Chord Chart URL</label>
                <input type="url" id="song-chord-chart" value={chordChartUrl} onChange={(e) => setChordChartUrl(e.target.value)} />
             </div>
             <div>
                <label htmlFor="song-youtube">YouTube URL</label>
                <input type="url" id="song-youtube" value={youtubeUrl} onChange={(e) => setYoutubeUrl(e.target.value)} />
             </div>
          </div>
          
          <div className="form-group">
            <label>Assign Singer(s)</label>
            <div className="checkbox-group">
              {(assignedPeopleForSingerRole && assignedPeopleForSingerRole.length > 0) ? (
                assignedPeopleForSingerRole.map(person => (
                  <label key={person.id} className="checkbox-label">
                    <input
                      type="checkbox"
                      value={person.id}
                      checked={selectedSingerIds.includes(person.id)}
                      onChange={() => handleSingerSelectionChange(person.id)}
                    />
                    {person.name}
                  </label>
                ))
              ) : (
                <p style={{fontStyle:'italic', color:'#94a3b8', fontSize:'0.9rem'}}>No singers assigned to this plan.</p>
              )}
            </div>
          </div>
        </>
      )}

      {type === 'Bible Verse' && (
        <div className="form-group" style={{display:'grid', gridTemplateColumns:'1fr 1fr 1fr', gap:'0.5rem'}}>
            <div><label>Book</label><input type="text" value={bibleBook} onChange={(e) => setBibleBook(e.target.value)} placeholder="John" required /></div>
            <div><label>Chapter</label><input type="text" value={bibleChapter} onChange={(e) => setBibleChapter(e.target.value)} placeholder="3" required /></div>
            <div><label>Verse(s)</label><input type="text" value={bibleVerseRange} onChange={(e) => setBibleVerseRange(e.target.value)} placeholder="16" required /></div>
        </div>
      )}

      {showDurationAndDetails && (
        <>
          <div className="form-group">
            <label htmlFor="item-duration">Duration (optional)</label>
            <input type="text" id="item-duration" value={duration} onChange={(e) => setDuration(e.target.value)} placeholder="e.g., 5 min" />
          </div>
          <div className="form-group">
            <label htmlFor="item-details">Details (optional)</label>
            <textarea id="item-details" value={details} onChange={(e) => setDetails(e.target.value)} />
          </div>
        </>
      )}

      <div className="form-actions">
          {type === 'Song' && (
             <button type="button" className="cancel-btn" onClick={handleStartImport} style={{marginRight:'auto'}}>
                 Import Info
              </button>
          )}
        {/* CANCEL BUTTON ADDED HERE */}
        <button type="button" className="cancel-btn" onClick={onCancel}>Cancel</button>
        <button type="submit" className="submit-btn">Add Item</button>
      </div>
    </form>
  );
};
export default AddItemForm;