// src/components/PlanPage/AddItemForm.jsx
import React, { useState, useEffect } from 'react';
import { supabase } from '../../supabaseClient';
import './AddItemForm.css'; 

const AddItemForm = ({ onAddItem, assignedPeopleForSingerRole, allAssignedPeople }) => {
  const [type, setType] = useState('Song');
  const [title, setTitle] = useState('');
  const [duration, setDuration] = useState('');
  const [details, setDetails] = useState('');

  // Song-specific state
  const [artist, setArtist] = useState('');
  const [chordChartUrl, setChordChartUrl] = useState('');
  const [youtubeUrl, setYoutubeUrl] = useState('');
  const [selectedSingerIds, setSelectedSingerIds] = useState([]); 

  // Bible Verse-specific state
  const [bibleBook, setBibleBook] = useState('');
  const [bibleChapter, setBibleChapter] = useState('');
  const [bibleVerseRange, setBibleVerseRange] = useState('');

  // Import Song Info State
  const [importMode, setImportMode] = useState('NONE'); // NONE, SELECT_MUSICIAN, SELECT_SONG
  const [importedMusicianId, setImportedMusicianId] = useState(null);
  const [availableImportSongs, setAvailableImportSongs] = useState([]);
  const [loadingImportSongs, setLoadingImportSongs] = useState(false);

  // Reset fields when type changes
  useEffect(() => {
    setArtist(''); setChordChartUrl(''); setYoutubeUrl(''); setSelectedSingerIds([]);
    setBibleBook(''); setBibleChapter(''); setBibleVerseRange('');
    setImportMode('NONE');

    if (type === 'Divider') {
      setDuration('');
      setDetails('');
      setTitle(currentTitle => (currentTitle === '' || !['Song', 'Bible Verse', 'Generic', 'Divider'].includes(type) ? '---' : currentTitle));
    } else if (title === '---' && type !== 'Divider') {
      setTitle('');
    }
  }, [type]); 

  const handleSingerSelectionChange = (singerId) => {
    setSelectedSingerIds(prevSelectedIds =>
      prevSelectedIds.includes(singerId)
        ? prevSelectedIds.filter(id => id !== singerId)
        : [...prevSelectedIds, singerId]
    );
  };

  const handleStartImport = () => {
    setImportMode('SELECT_MUSICIAN');
  };

  const handleMusicianSelect = async (musicianId) => {
    setImportedMusicianId(musicianId);
    setLoadingImportSongs(true);
    setImportMode('SELECT_SONG');
    try {
        const { data, error } = await supabase
            .from('songs')
            .select('*')
            .eq('added_by_user_id', musicianId)
            .eq('is_primary', false)
            .order('title', { ascending: true });
        
        if (error) throw error;
        setAvailableImportSongs(data || []);
    } catch (err) {
        alert('Failed to fetch songs for this musician: ' + err.message);
        setImportMode('SELECT_MUSICIAN');
    } finally {
        setLoadingImportSongs(false);
    }
  };

  const handleSongImportSelect = (song) => {
      setTitle(song.title || '');
      setArtist(song.artist || '');
      setChordChartUrl(song.chord_chart_url || '');
      setYoutubeUrl(song.youtube_url || '');
      setImportMode('NONE');
      setAvailableImportSongs([]);
      setImportedMusicianId(null);
  };

  const handleCancelImport = () => {
      setImportMode('NONE');
      setAvailableImportSongs([]);
      setImportedMusicianId(null);
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    let autoGeneratedTitle = title.trim();
    if (type === 'Bible Verse' && !autoGeneratedTitle && bibleBook.trim() && bibleChapter.trim() && bibleVerseRange.trim()) {
        autoGeneratedTitle = `${bibleBook.trim()} ${bibleChapter.trim()}:${bibleVerseRange.trim()}`;
    }

    if (type !== 'Divider' && type !== 'Bible Verse' && !autoGeneratedTitle) {
      alert('Please enter a title for the item.');
      return;
    }
    if (type === 'Bible Verse' && (!bibleBook.trim() || !bibleChapter.trim() || !bibleVerseRange.trim())) {
      alert('Please fill in Book, Chapter, and Verse(s) for a Bible Verse item.');
      return;
    }

    let newItemData = {
      type,
      title: type === 'Divider' ? (title.trim() || '---') : autoGeneratedTitle,
      duration: (type === 'Divider' || type === 'Bible Verse') ? null : (duration.trim() || null),
      details: (type === 'Divider' || type === 'Bible Verse') ? null : (details.trim() || null),
      artist: null, chord_chart_url: null, youtube_url: null, assigned_singer_ids: [], musical_key: null,
      bible_book: null, bible_chapter: null, bible_verse_range: null,
    };

    if (type === 'Song') {
      newItemData.artist = artist.trim() || null;
      newItemData.chord_chart_url = chordChartUrl.trim() || null;
      newItemData.youtube_url = youtubeUrl.trim() || null;
      newItemData.assigned_singer_ids = selectedSingerIds; 
    } else if (type === 'Bible Verse') {
      newItemData.bible_book = bibleBook.trim();
      newItemData.bible_chapter = bibleChapter.trim();
      newItemData.bible_verse_range = bibleVerseRange.trim();
    }

    onAddItem(newItemData);

    setTitle(type === 'Divider' ? '---' : '');
    setDuration('');
    setDetails('');
    setArtist(''); setChordChartUrl(''); setYoutubeUrl(''); setSelectedSingerIds([]);
    setBibleBook(''); setBibleChapter(''); setBibleVerseRange('');
  };

  const showTitleInput = type !== 'Divider';
  const showDurationAndDetails = type === 'Generic' || type === 'Song' || type === 'Bible Verse';

  // --- Render Import Views ---
  if (importMode === 'SELECT_MUSICIAN') {
      // Deduplicate musicians by ID
      const uniqueMusicians = [];
      const map = new Map();
      if (allAssignedPeople) {
          for (const person of allAssignedPeople) {
              if(!map.has(person.id)){
                  map.set(person.id, true);
                  uniqueMusicians.push(person);
              }
          }
      }

      return (
          <div className="add-item-form import-view">
              <h3>Import Song Info</h3>
              <p>Select a musician to view their songs:</p>
              <div className="import-list">
                  {uniqueMusicians.length > 0 ? (
                      uniqueMusicians.map(musician => (
                          <button key={musician.id} type="button" className="import-list-item-btn" onClick={() => handleMusicianSelect(musician.id)}>
                              {musician.name} <span className="role-tag">({musician.role})</span>
                          </button>
                      ))
                  ) : (
                      <p>No musicians assigned to this plan.</p>
                  )}
              </div>
              <button type="button" className="cancel-btn" onClick={handleCancelImport} style={{marginTop: '15px', width: '100%'}}>Cancel</button>
          </div>
      );
  }

  if (importMode === 'SELECT_SONG') {
      return (
          <div className="add-item-form import-view">
              <h3>Select a Song</h3>
              {loadingImportSongs ? <p>Loading songs...</p> : (
                  <div className="import-list">
                      {availableImportSongs.length > 0 ? (
                          availableImportSongs.map(song => (
                              <button key={song.id} type="button" className="import-list-item-btn" onClick={() => handleSongImportSelect(song)}>
                                  <strong>{song.title}</strong>
                                  {song.artist && <span style={{display:'block', fontSize:'0.85em', color:'#666'}}>{song.artist}</span>}
                              </button>
                          ))
                      ) : (
                          <p>No secondary songs found for this musician.</p>
                      )}
                  </div>
              )}
               <button type="button" className="cancel-btn" onClick={() => setImportMode('SELECT_MUSICIAN')} style={{marginTop: '15px', width: '100%'}}>Back</button>
          </div>
      )
  }

  // --- Render Main Form ---
  return (
    <form onSubmit={handleSubmit} className="add-item-form">
      <h3>Add New Service Item</h3>
      <div className="form-group">
        <label htmlFor="item-type">Type:</label>
        <select id="item-type" value={type} onChange={(e) => setType(e.target.value)}>
          <option value="Generic">Service Item</option>
          <option value="Song">Song</option>
          <option value="Bible Verse">Bible Verse</option>
          <option value="Divider">Divider</option>
        </select>
      </div>

      {showTitleInput && (
        <div className="form-group">
            <label htmlFor="item-title">
                {type === 'Song' ? 'Song Title:' : 
                (type === 'Bible Verse' ? 'Reading Title (optional - e.g., Gospel Reading):' : 'Title:')}
            </label>
            <input
              type="text"
              id="item-title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              required={type === 'Generic' || type === 'Song'}
            />
        </div>
      )}
      {type === 'Divider' && (
         <div className="form-group">
            <label htmlFor="item-title">Divider Text (Optional):</label>
            <input
              type="text"
              id="item-title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g., ---, Transition, Offering"
            />
        </div>
      )}

      {type === 'Song' && (
        <>
          <div className="form-group">
            <label htmlFor="song-artist">Artist:</label>
            <input type="text" id="song-artist" value={artist} onChange={(e) => setArtist(e.target.value)} placeholder="e.g., Hillsong, Chris Tomlin" />
          </div>
          <div className="form-group">
            <label htmlFor="song-chord-chart">Chord Chart URL:</label>
            <input type="url" id="song-chord-chart" value={chordChartUrl} onChange={(e) => setChordChartUrl(e.target.value)} placeholder="https://example.com/chords" />
          </div>
          <div className="form-group">
            <label htmlFor="song-youtube">YouTube URL:</label>
            <input type="url" id="song-youtube" value={youtubeUrl} onChange={(e) => setYoutubeUrl(e.target.value)} placeholder="https://www.youtube.com/watch?v=..." />
          </div>
          <div className="form-group">
            <label>Assign Singer(s) (must have "Vocals" for this event):</label>
            <div className="checkbox-group multi-select-singer-group">
              {(assignedPeopleForSingerRole && assignedPeopleForSingerRole.length > 0) ? (
                assignedPeopleForSingerRole.map(person => (
                  <label key={person.id} className="checkbox-label">
                    <input
                      type="checkbox"
                      value={person.id}
                      checked={selectedSingerIds.includes(person.id)}
                      onChange={() => handleSingerSelectionChange(person.id)}
                    />
                    {person.name}
                  </label>
                ))
              ) : (
                <p className="no-singers-message">No team members assigned "Vocals" for this plan yet, or none are pending/accepted.</p>
              )}
            </div>
          </div>
        </>
      )}

      {type === 'Bible Verse' && (
        <>
          <div className="form-group">
            <label htmlFor="bible-book">Book:</label>
            <input type="text" id="bible-book" value={bibleBook} onChange={(e) => setBibleBook(e.target.value)} placeholder="e.g., John" required />
          </div>
          <div className="form-group">
            <label htmlFor="bible-chapter">Chapter:</label>
            <input type="text" id="bible-chapter" value={bibleChapter} onChange={(e) => setBibleChapter(e.target.value)} placeholder="e.g., 3" required />
          </div>
          <div className="form-group">
            <label htmlFor="bible-verse-range">Verse(s):</label>
            <input type="text" id="bible-verse-range" value={bibleVerseRange} onChange={(e) => setBibleVerseRange(e.target.value)} placeholder="e.g., 16 or 16-18" required />
          </div>
        </>
      )}

      {showDurationAndDetails && (
        <>
          <div className="form-group">
            <label htmlFor="item-duration">Duration (optional):</label>
            <input type="text" id="item-duration" value={duration} onChange={(e) => setDuration(e.target.value)} placeholder="e.g., 5 min" />
          </div>
          <div className="form-group">
            <label htmlFor="item-details">Details (optional):</label>
            <textarea id="item-details" value={details} onChange={(e) => setDetails(e.target.value)} />
          </div>
        </>
      )}
      <div className="form-actions">
          {type === 'Song' && (
          <>
             <button type="button" className="import-song-btn" onClick={handleStartImport} style={{fontSize: '0.9em', padding: '5px 10px', cursor:'pointer', backgroundColor: '#f0f0f0', border:'1px solid #ccc', borderRadius:'4px'}}>
                 Import
              </button>
          </>
          )}
        <button type="submit" className="submit-btn">Add Item</button>
      </div>
    </form>
  );
};
export default AddItemForm;