// src/components/PlanPage/AddItemForm.jsx
import React, { useState, useEffect } from 'react';
import './AddItemForm.css'; // Ensure this CSS file has necessary styles for form-group etc.

const AddItemForm = ({ onAddItem, assignedPeople }) => {
  const [type, setType] = useState('Generic'); // Default to Generic "Service Item"
  const [title, setTitle] = useState('');
  const [duration, setDuration] = useState('');
  const [details, setDetails] = useState('');

  // Song-specific state
  const [artist, setArtist] = useState('');
  const [chordChartUrl, setChordChartUrl] = useState('');
  const [youtubeUrl, setYoutubeUrl] = useState('');
  const [selectedSingerId, setSelectedSingerId] = useState('');

  // Bible Verse-specific state
  const [bibleBook, setBibleBook] = useState('');
  const [bibleChapter, setBibleChapter] = useState('');
  const [bibleVerseRange, setBibleVerseRange] = useState('');

  // Reset fields when type changes
  useEffect(() => {
    // Reset all specific fields first
    setArtist(''); setChordChartUrl(''); setYoutubeUrl(''); setSelectedSingerId('');
    setBibleBook(''); setBibleChapter(''); setBibleVerseRange('');

    if (type === 'Divider') {
      setDuration('');
      setDetails('');
      // Set a default title for divider, or clear if previous title was not a typical one
      if (title === '' || !['Song', 'Bible Verse', 'Generic'].includes(type)) { // Basic check
          setTitle('---');
      }
    } else if (title === '---' && type !== 'Divider') {
      setTitle(''); // Clear default divider title if type changes
    }
  }, [type]); // Removed title from dependency here to simplify reset logic based on type only

  const handleSubmit = (e) => {
    e.preventDefault();

    if (type !== 'Divider' && type !== 'Bible Verse' && !title.trim()) {
      alert('Please enter a title for the item.');
      return;
    }
    if (type === 'Bible Verse' && (!bibleBook.trim() || !bibleChapter.trim() || !bibleVerseRange.trim())) {
      alert('Please fill in Book, Chapter, and Verse(s) for a Bible Verse item.');
      return;
    }

    let autoGeneratedTitle = title.trim();
    if (type === 'Bible Verse' && !autoGeneratedTitle) {
        autoGeneratedTitle = `${bibleBook.trim()} ${bibleChapter.trim()}:${bibleVerseRange.trim()}`;
    }


    let newItemData = {
      type,
      title: type === 'Divider' ? (title.trim() || '---') : autoGeneratedTitle,
      duration: (type === 'Divider' || type === 'Bible Verse') ? null : (duration.trim() || null),
      details: (type === 'Divider' || type === 'Bible Verse') ? null : (details.trim() || null),
      artist: null, chord_chart_url: null, youtube_url: null, assigned_singer_person_id: null, musical_key: null,
      bible_book: null, bible_chapter: null, bible_verse_range: null,
    };

    if (type === 'Song') {
      newItemData.artist = artist.trim() || null;
      newItemData.chord_chart_url = chordChartUrl.trim() || null;
      newItemData.youtube_url = youtubeUrl.trim() || null;
      newItemData.assigned_singer_person_id = selectedSingerId || null;
    } else if (type === 'Bible Verse') {
      newItemData.bible_book = bibleBook.trim();
      newItemData.bible_chapter = bibleChapter.trim();
      newItemData.bible_verse_range = bibleVerseRange.trim();
    }

    onAddItem(newItemData);

    // Reset form fields after submission
    setTitle(type === 'Divider' ? '---' : '');
    setDuration('');
    setDetails('');
    setArtist(''); setChordChartUrl(''); setYoutubeUrl(''); setSelectedSingerId('');
    setBibleBook(''); setBibleChapter(''); setBibleVerseRange('');
    // Consider resetting type to 'Generic' if desired, or keep last selected type
    // setType('Generic');
  };

  const showTitleInput = type !== 'Divider';
  const showDurationAndDetails = type === 'Generic' || type === 'Song';

  return (
    <form onSubmit={handleSubmit} className="add-item-form">
      <h3>Add New Service Item</h3>
      <div className="form-group">
        <label htmlFor="item-type">Type:</label>
        <select id="item-type" value={type} onChange={(e) => setType(e.target.value)}>
          <option value="Generic">Service Item</option>
          <option value="Song">Song</option>
          <option value="Bible Verse">Bible Verse</option>
          <option value="Divider">Divider</option>
        </select>
      </div>

      {showTitleInput && (
        <div className="form-group">
            <label htmlFor="item-title">
                {type === 'Song' ? 'Song Title:' :
                (type === 'Bible Verse' ? 'Reading Title (optional, e.g., Gospel Reading):' : 'Title:')}
            </label>
            <input
              type="text"
              id="item-title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              required={type === 'Generic' || type === 'Song'} // Title required for these types
            />
        </div>
      )}
      {type === 'Divider' && (
         <div className="form-group">
            <label htmlFor="item-title">Divider Text (Optional):</label>
            <input
            type="text"
            id="item-title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="e.g., ---, Transition, Offering"
            />
        </div>
      )}

      {/* --- JSX for Song Type --- */}
      {type === 'Song' && (
        <>
          <div className="form-group">
            <label htmlFor="song-artist">Artist:</label>
            <input
              type="text"
              id="song-artist"
              value={artist}
              onChange={(e) => setArtist(e.target.value)}
              placeholder="e.g., Hillsong, Chris Tomlin"
            />
          </div>
          <div className="form-group">
            <label htmlFor="song-chord-chart">Chord Chart URL:</label>
            <input
              type="url"
              id="song-chord-chart"
              value={chordChartUrl}
              onChange={(e) => setChordChartUrl(e.target.value)}
              placeholder="https://example.com/chords"
            />
          </div>
          <div className="form-group">
            <label htmlFor="song-youtube">YouTube URL:</label>
            <input
              type="url"
              id="song-youtube"
              value={youtubeUrl}
              onChange={(e) => setYoutubeUrl(e.target.value)}
              placeholder="https://www.youtube.com/watch?v=..."
            />
          </div>
          <div className="form-group">
            <label htmlFor="song-singer">Assign Singer (Optional):</label>
            <select
              id="song-singer"
              value={selectedSingerId}
              onChange={(e) => setSelectedSingerId(e.target.value)}
            >
              <option value="">-- Select a singer --</option>
              {assignedPeople && assignedPeople.map(person => (
                <option key={person.id} value={person.id}>
                  {person.name} ({person.role})
                </option>
              ))}
            </select>
          </div>
        </>
      )}
      {/* --- End JSX for Song Type --- */}

      {/* --- JSX for Bible Verse Type --- */}
      {type === 'Bible Verse' && (
        <>
          <div className="form-group">
            <label htmlFor="bible-book">Book:</label>
            <input
              type="text"
              id="bible-book"
              value={bibleBook}
              onChange={(e) => setBibleBook(e.target.value)}
              placeholder="e.g., John"
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="bible-chapter">Chapter:</label>
            <input
              type="text" // Using text for flexibility e.g., Psalm 119
              id="bible-chapter"
              value={bibleChapter}
              onChange={(e) => setBibleChapter(e.target.value)}
              placeholder="e.g., 3"
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="bible-verse-range">Verse(s):</label>
            <input
              type="text"
              id="bible-verse-range"
              value={bibleVerseRange}
              onChange={(e) => setBibleVerseRange(e.target.value)}
              placeholder="e.g., 16 or 16-18"
              required
            />
          </div>
        </>
      )}
      {/* --- End JSX for Bible Verse Type --- */}

      {showDurationAndDetails && (
        <>
          <div className="form-group">
            <label htmlFor="item-duration">Duration (optional):</label>
            <input
              type="text"
              id="item-duration"
              value={duration}
              onChange={(e) => setDuration(e.target.value)}
              placeholder="e.g., 5 min"
            />
          </div>
          <div className="form-group">
            <label htmlFor="item-details">Details (optional):</label>
            <textarea
              id="item-details"
              value={details}
              onChange={(e) => setDetails(e.target.value)}
            />
          </div>
        </>
      )}
      <div className="form-actions">
        <button type="submit" className="submit-btn">Add Item</button>
      </div>
    </form>
  );
};

export default AddItemForm;