// src/components/PlanPage/EditServiceItemForm.jsx
import React, { useState, useEffect } from 'react';
import { supabase } from '../../supabaseClient';
import './AddItemForm.css'; 

const EditServiceItemForm = ({ itemToEdit, onUpdateItem, onCancel, assignedPeopleForSingerRole, allAssignedPeople }) => {
  const [title, setTitle] = useState('');
  const [duration, setDuration] = useState('');
  const [details, setDetails] = useState('');

  // Song-specific fields
  const [artist, setArtist] = useState('');
  const [chordChartUrl, setChordChartUrl] = useState('');
  const [youtubeUrl, setYoutubeUrl] = useState('');
  const [selectedSingerIds, setSelectedSingerIds] = useState([]); 

  // Bible Verse-specific fields
  const [bibleBook, setBibleBook] = useState('');
  const [bibleChapter, setBibleChapter] = useState('');
  const [bibleVerseRange, setBibleVerseRange] = useState('');

  const [isSubmitting, setIsSubmitting] = useState(false);

  // Import Song Info State
  const [importMode, setImportMode] = useState('NONE'); // NONE, SELECT_MUSICIAN, SELECT_SONG
  const [importedMusicianId, setImportedMusicianId] = useState(null);
  const [availableImportSongs, setAvailableImportSongs] = useState([]);
  const [loadingImportSongs, setLoadingImportSongs] = useState(false);

  useEffect(() => {
    if (itemToEdit) {
      setTitle(itemToEdit.title || (itemToEdit.type === 'Divider' ? '---' : ''));
      setDuration(itemToEdit.duration || '');
      setDetails(itemToEdit.details || '');

      setArtist(itemToEdit.type === 'Song' ? itemToEdit.artist || '' : '');
      setChordChartUrl(itemToEdit.type === 'Song' ? itemToEdit.chord_chart_url || '' : '');
      setYoutubeUrl(itemToEdit.type === 'Song' ? itemToEdit.youtube_url || '' : '');
      setSelectedSingerIds(itemToEdit.type === 'Song' ? itemToEdit.assigned_singer_ids || [] : []);

      setBibleBook(itemToEdit.type === 'Bible Verse' ? itemToEdit.bible_book || '' : '');
      setBibleChapter(itemToEdit.type === 'Bible Verse' ? itemToEdit.bible_chapter || '' : '');
      setBibleVerseRange(itemToEdit.type === 'Bible Verse' ? itemToEdit.bible_verse_range || '' : '');
    }
  }, [itemToEdit]);

  const handleSingerSelectionChange = (singerId) => {
    setSelectedSingerIds(prevSelectedIds =>
      prevSelectedIds.includes(singerId)
        ? prevSelectedIds.filter(id => id !== singerId)
        : [...prevSelectedIds, singerId]
    );
  };

  const handleStartImport = () => {
    setImportMode('SELECT_MUSICIAN');
  };

  const handleMusicianSelect = async (musicianId) => {
    setImportedMusicianId(musicianId);
    setLoadingImportSongs(true);
    setImportMode('SELECT_SONG');
    try {
        const { data, error } = await supabase
            .from('songs')
            .select('*')
            .eq('added_by_user_id', musicianId)
            .eq('is_primary', false)
            .order('title', { ascending: true });
        
        if (error) throw error;
        setAvailableImportSongs(data || []);
    } catch (err) {
        alert('Failed to fetch songs for this musician: ' + err.message);
        setImportMode('SELECT_MUSICIAN');
    } finally {
        setLoadingImportSongs(false);
    }
  };

  const handleSongImportSelect = (song) => {
      setTitle(song.title || '');
      setArtist(song.artist || '');
      setChordChartUrl(song.chord_chart_url || '');
      setYoutubeUrl(song.youtube_url || '');
      setImportMode('NONE');
      setAvailableImportSongs([]);
      setImportedMusicianId(null);
  };

  const handleCancelImport = () => {
      setImportMode('NONE');
      setAvailableImportSongs([]);
      setImportedMusicianId(null);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    let autoGeneratedTitle = title.trim();
    if (itemToEdit.type === 'Bible Verse' && !autoGeneratedTitle && bibleBook.trim() && bibleChapter.trim() && bibleVerseRange.trim()) {
        autoGeneratedTitle = `${bibleBook.trim()} ${bibleChapter.trim()}:${bibleVerseRange.trim()}`;
    }

    if (itemToEdit.type !== 'Divider' && itemToEdit.type !== 'Bible Verse' && !autoGeneratedTitle) {
      alert('Please enter a title for the item.');
      return;
    }
    if (itemToEdit.type === 'Bible Verse' && (!bibleBook.trim() || !bibleChapter.trim() || !bibleVerseRange.trim())) {
      alert('Please fill in Book, Chapter, and Verse(s) for a Bible Verse item.');
      return;
    }
    setIsSubmitting(true);

    let payload = {
      title: itemToEdit.type === 'Divider' ? (title.trim() || '---') : autoGeneratedTitle,
      duration: (itemToEdit.type === 'Divider') ? null : (duration.trim() || null),
      details: (itemToEdit.type === 'Divider') ? null : (details.trim() || null),
      artist: itemToEdit.type === 'Song' ? (artist.trim() || null) : null,
      chord_chart_url: itemToEdit.type === 'Song' ? (chordChartUrl.trim() || null) : null,
      youtube_url: itemToEdit.type === 'Song' ? (youtubeUrl.trim() || null) : null,
      assigned_singer_ids: itemToEdit.type === 'Song' ? selectedSingerIds : [], // Send empty array if not a song
      bible_book: itemToEdit.type === 'Bible Verse' ? (bibleBook.trim() || null) : null,
      bible_chapter: itemToEdit.type === 'Bible Verse' ? (bibleChapter.trim() || null) : null,
      bible_verse_range: itemToEdit.type === 'Bible Verse' ? (bibleVerseRange.trim() || null) : null,
      musical_key: itemToEdit.musical_key, // Preserve existing key, edited inline
    };

    try {
      await onUpdateItem(payload);
    } catch (error) {
      // Error alert handled by PlanPage
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!itemToEdit) return null;

  const showTitleInput = itemToEdit.type !== 'Divider';
  const showDurationAndDetails = itemToEdit.type === 'Generic' || itemToEdit.type === 'Song' || itemToEdit.type === 'Bible Verse';

  // --- Render Import Views ---
  if (importMode === 'SELECT_MUSICIAN') {
    // Deduplicate musicians by ID
    const uniqueMusicians = [];
    const map = new Map();
    if (allAssignedPeople) {
        for (const person of allAssignedPeople) {
            if(!map.has(person.id)){
                map.set(person.id, true);
                uniqueMusicians.push(person);
            }
        }
    }

    return (
        <div className="add-item-form edit-item-form import-view">
            <h3>Import Song Info</h3>
            <p>Select a musician to view their songs:</p>
            <div className="import-list">
                {uniqueMusicians.length > 0 ? (
                    uniqueMusicians.map(musician => (
                        <button key={musician.id} type="button" className="import-list-item-btn" onClick={() => handleMusicianSelect(musician.id)}>
                            {musician.name} <span className="role-tag">({musician.role})</span>
                        </button>
                    ))
                ) : (
                    <p>No musicians assigned to this plan.</p>
                )}
            </div>
            <button type="button" className="cancel-btn" onClick={handleCancelImport} style={{marginTop: '15px', width: '100%'}}>Cancel</button>
        </div>
    );
  }

  if (importMode === 'SELECT_SONG') {
    return (
        <div className="add-item-form edit-item-form import-view">
            <h3>Select a Song</h3>
            {loadingImportSongs ? <p>Loading songs...</p> : (
                <div className="import-list">
                    {availableImportSongs.length > 0 ? (
                        availableImportSongs.map(song => (
                            <button key={song.id} type="button" className="import-list-item-btn" onClick={() => handleSongImportSelect(song)}>
                                <strong>{song.title}</strong>
                                {song.artist && <span style={{display:'block', fontSize:'0.85em', color:'#666'}}>{song.artist}</span>}
                            </button>
                        ))
                    ) : (
                        <p>No secondary songs found for this musician.</p>
                    )}
                </div>
            )}
             <button type="button" className="cancel-btn" onClick={() => setImportMode('SELECT_MUSICIAN')} style={{marginTop: '15px', width: '100%'}}>Back</button>
        </div>
    )
  }

  // --- Main Form Render ---
  return (
    <form onSubmit={handleSubmit} className="add-item-form edit-item-form">
      <h3>Edit: {itemToEdit.title || itemToEdit.type}</h3>
      <p style={{ marginBottom: '15px', color: '#555', fontSize: '0.9em' }}>
        Type: <strong>{itemToEdit.type}</strong> (Cannot be changed during edit)
      </p>

      {showTitleInput && (
        <div className="form-group">
          <label htmlFor="edit-item-title">
            {itemToEdit.type === 'Song' ? 'Song Title:' : 
            (itemToEdit.type === 'Bible Verse' ? 'Reading Title (optional):' : 'Title:')}
          </label>
          <input type="text" id="edit-item-title" value={title} onChange={(e) => setTitle(e.target.value)} required={itemToEdit.type === 'Generic' || itemToEdit.type === 'Song'}/>
        </div>
      )}
      {itemToEdit.type === 'Divider' && (
         <div className="form-group">
            <label htmlFor="edit-item-title">Divider Text (Optional):</label>
            <input type="text" id="edit-item-title" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g., ---, Transition"/>
        </div>
      )}

      {itemToEdit.type === 'Song' && (
        <>
          <div className="form-group">
            <label htmlFor="edit-song-artist">Artist:</label>
            <input type="text" id="edit-song-artist" value={artist} onChange={(e) => setArtist(e.target.value)} />
          </div>
          <div className="form-group">
            <label htmlFor="edit-song-chord-chart">Chord Chart URL:</label>
            <input type="url" id="edit-song-chord-chart" value={chordChartUrl} onChange={(e) => setChordChartUrl(e.target.value)} />
          </div>
          <div className="form-group">
            <label htmlFor="edit-song-youtube">YouTube URL:</label>
            <input type="url" id="edit-song-youtube" value={youtubeUrl} onChange={(e) => setYoutubeUrl(e.target.value)} />
          </div>
          <div className="form-group">
            <label>Assign Singer(s) (must have "Vocals" for this event):</label>
            <div className="checkbox-group multi-select-singer-group">
              {(assignedPeopleForSingerRole && assignedPeopleForSingerRole.length > 0) ? (
                assignedPeopleForSingerRole.map(person => (
                  <label key={person.id} className="checkbox-label">
                    <input
                      type="checkbox"
                      value={person.id}
                      checked={selectedSingerIds.includes(person.id)}
                      onChange={() => handleSingerSelectionChange(person.id)}
                    />
                    {person.name}
                  </label>
                ))
              ) : (
                 <p className="no-singers-message">No team members assigned "Vocals" for this plan yet, or none are pending/accepted.</p>
              )}
            </div>
          </div>
        </>
      )}

      {itemToEdit.type === 'Bible Verse' && (
        <>
          <div className="form-group">
            <label htmlFor="edit-bible-book">Book:</label>
            <input type="text" id="edit-bible-book" value={bibleBook} onChange={(e) => setBibleBook(e.target.value)} required />
          </div>
          <div className="form-group">
            <label htmlFor="edit-bible-chapter">Chapter:</label>
            <input type="text" id="edit-bible-chapter" value={bibleChapter} onChange={(e) => setBibleChapter(e.target.value)} required />
          </div>
          <div className="form-group">
            <label htmlFor="edit-bible-verse-range">Verse(s):</label>
            <input type="text" id="edit-bible-verse-range" value={bibleVerseRange} onChange={(e) => setBibleVerseRange(e.target.value)} required />
          </div>
        </>
      )}

      {showDurationAndDetails && (
        <>
          <div className="form-group">
            <label htmlFor="edit-item-duration">Duration (optional):</label>
            <input type="text" id="edit-item-duration" value={duration} onChange={(e) => setDuration(e.target.value)} />
          </div>
          <div className="form-group">
            <label htmlFor="edit-item-details">Details (optional):</label>
            <textarea id="edit-item-details" value={details} onChange={(e) => setDetails(e.target.value)} />
          </div>
        </>
      )}

      <div className="form-actions" style={{ marginTop: '20px' }}>
        {itemToEdit.type === 'Song' && (
          <>
            <button type="button" className="import-song-btn" onClick={handleStartImport} style={{fontSize: '0.9em', padding: '5px 10px', cursor:'pointer', backgroundColor: '#f0f0f0', border:'1px solid #ccc', borderRadius:'4px'}}>
              Import
            </button>
          </>
        )}
        
        <button type="submit" className="submit-btn" disabled={isSubmitting}>
          {isSubmitting ? 'Saving...' : 'Save Changes'}
        </button>
        <button type="button" className="cancel-btn" onClick={onCancel} disabled={isSubmitting}>
          Cancel
        </button>
      </div>
    </form>
  );
};

export default EditServiceItemForm;