// src/components/PlanPage/EditServiceItemForm.jsx
import React, { useState, useEffect } from 'react';
import { supabase } from '../../supabaseClient';
// CSS handled by PlanPage.css (Shared Form Styles)

const EditServiceItemForm = ({ itemToEdit, onUpdateItem, onCancel, assignedPeopleForSingerRole, allAssignedPeople }) => {
  // ... (Keep existing state logic) ...
  const [title, setTitle] = useState('');
  const [duration, setDuration] = useState('');
  const [details, setDetails] = useState('');
  const [artist, setArtist] = useState('');
  const [chordChartUrl, setChordChartUrl] = useState('');
  const [youtubeUrl, setYoutubeUrl] = useState('');
  const [selectedSingerIds, setSelectedSingerIds] = useState([]); 
  const [bibleBook, setBibleBook] = useState('');
  const [bibleChapter, setBibleChapter] = useState('');
  const [bibleVerseRange, setBibleVerseRange] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [importMode, setImportMode] = useState('NONE'); 
  const [importedMusicianId, setImportedMusicianId] = useState(null);
  const [availableImportSongs, setAvailableImportSongs] = useState([]);
  const [loadingImportSongs, setLoadingImportSongs] = useState(false);

  useEffect(() => {
    if (itemToEdit) {
      setTitle(itemToEdit.title || (itemToEdit.type === 'Divider' ? '---' : ''));
      setDuration(itemToEdit.duration || '');
      setDetails(itemToEdit.details || '');
      setArtist(itemToEdit.type === 'Song' ? itemToEdit.artist || '' : '');
      setChordChartUrl(itemToEdit.type === 'Song' ? itemToEdit.chord_chart_url || '' : '');
      setYoutubeUrl(itemToEdit.type === 'Song' ? itemToEdit.youtube_url || '' : '');
      setSelectedSingerIds(itemToEdit.type === 'Song' ? itemToEdit.assigned_singer_ids || [] : []);
      setBibleBook(itemToEdit.type === 'Bible Verse' ? itemToEdit.bible_book || '' : '');
      setBibleChapter(itemToEdit.type === 'Bible Verse' ? itemToEdit.bible_chapter || '' : '');
      setBibleVerseRange(itemToEdit.type === 'Bible Verse' ? itemToEdit.bible_verse_range || '' : '');
    }
  }, [itemToEdit]);

  // ... (Keep existing handler logic: handleSingerSelectionChange, handleStartImport, etc) ...
  const handleSingerSelectionChange = (singerId) => { setSelectedSingerIds(prev => prev.includes(singerId) ? prev.filter(id => id !== singerId) : [...prev, singerId]); };
  const handleStartImport = () => setImportMode('SELECT_MUSICIAN');
  const handleMusicianSelect = async (musicianId) => {
    setImportedMusicianId(musicianId); setLoadingImportSongs(true); setImportMode('SELECT_SONG');
    try {
        const { data, error } = await supabase.from('songs').select('*').eq('added_by_user_id', musicianId).eq('is_primary', false).order('title', { ascending: true });
        if (error) throw error; setAvailableImportSongs(data || []);
    } catch (err) { alert(err.message); setImportMode('SELECT_MUSICIAN'); } finally { setLoadingImportSongs(false); }
  };
  const handleSongImportSelect = (song) => {
      setTitle(song.title || ''); setArtist(song.artist || ''); setChordChartUrl(song.chord_chart_url || '');
      setYoutubeUrl(song.youtube_url || ''); setImportMode('NONE'); setAvailableImportSongs([]); setImportedMusicianId(null);
  };
  const handleCancelImport = () => { setImportMode('NONE'); setAvailableImportSongs([]); setImportedMusicianId(null); };

  const handleSubmit = async (e) => {
    e.preventDefault();
    let autoGeneratedTitle = title.trim();
    if (itemToEdit.type === 'Bible Verse' && !autoGeneratedTitle && bibleBook.trim()) {
        autoGeneratedTitle = `${bibleBook.trim()} ${bibleChapter.trim()}:${bibleVerseRange.trim()}`;
    }
    if (itemToEdit.type !== 'Divider' && itemToEdit.type !== 'Bible Verse' && !autoGeneratedTitle) { alert('Title required'); return; }
    setIsSubmitting(true);
    // ... Payload construction ...
    let payload = {
      title: itemToEdit.type === 'Divider' ? (title.trim() || '---') : autoGeneratedTitle,
      duration: (itemToEdit.type === 'Divider') ? null : (duration.trim() || null),
      details: (itemToEdit.type === 'Divider') ? null : (details.trim() || null),
      artist: itemToEdit.type === 'Song' ? (artist.trim() || null) : null,
      chord_chart_url: itemToEdit.type === 'Song' ? (chordChartUrl.trim() || null) : null,
      youtube_url: itemToEdit.type === 'Song' ? (youtubeUrl.trim() || null) : null,
      assigned_singer_ids: itemToEdit.type === 'Song' ? selectedSingerIds : [],
      bible_book: itemToEdit.type === 'Bible Verse' ? (bibleBook.trim() || null) : null,
      bible_chapter: itemToEdit.type === 'Bible Verse' ? (bibleChapter.trim() || null) : null,
      bible_verse_range: itemToEdit.type === 'Bible Verse' ? (bibleVerseRange.trim() || null) : null,
      musical_key: itemToEdit.musical_key,
    };
    try { await onUpdateItem(payload); } catch (error) { /* handled by parent */ } finally { setIsSubmitting(false); }
  };

  if (!itemToEdit) return null;
  const showTitleInput = itemToEdit.type !== 'Divider';
  const showDurationAndDetails = itemToEdit.type === 'Generic' || itemToEdit.type === 'Song' || itemToEdit.type === 'Bible Verse';

  // --- RENDER (Import Mode logic same as AddItemForm) ---
  if (importMode === 'SELECT_MUSICIAN') {
    // ... (same as AddItemForm) ...
    const uniqueMusicians = []; const map = new Map();
    if (allAssignedPeople) { allAssignedPeople.forEach(p => { if(!map.has(p.id)){ map.set(p.id, true); uniqueMusicians.push(p); } }); }
    return (
        <div className="glass-form import-view">
            <h3>Import Song Info</h3>
            <p className="form-group">Select a musician:</p>
            <div className="import-list">
                {uniqueMusicians.length > 0 ? uniqueMusicians.map(m => (
                    <button key={m.id} type="button" className="import-list-item-btn" onClick={() => handleMusicianSelect(m.id)}>
                        {m.name} <span className="role-tag">({m.role})</span>
                    </button>
                )) : <p>No musicians assigned.</p>}
            </div>
            <button type="button" className="cancel-btn" style={{width: '100%'}} onClick={handleCancelImport}>Cancel</button>
        </div>
    );
  }

  if (importMode === 'SELECT_SONG') {
      return (
          <div className="glass-form import-view">
              <h3>Select a Song</h3>
              {loadingImportSongs ? <p>Loading...</p> : (
                  <div className="import-list">
                      {availableImportSongs.map(s => (
                          <button key={s.id} type="button" className="import-list-item-btn" onClick={() => handleSongImportSelect(s)}>
                              <strong>{s.title}</strong>
                              {s.artist && <span style={{display:'block', fontSize:'0.8em', color:'#64748b'}}>{s.artist}</span>}
                          </button>
                      ))}
                  </div>
              )}
               <button type="button" className="cancel-btn" style={{width: '100%'}} onClick={() => setImportMode('SELECT_MUSICIAN')}>Back</button>
          </div>
      )
  }

  // --- Main Render ---
  return (
    <form onSubmit={handleSubmit} className="glass-form">
      <h3>Edit: {itemToEdit.type}</h3>
      
      {showTitleInput && (
        <div className="form-group">
          <label>{itemToEdit.type === 'Song' ? 'Song Title' : 'Title'}</label>
          <input type="text" value={title} onChange={(e) => setTitle(e.target.value)} required />
        </div>
      )}
      {itemToEdit.type === 'Divider' && (
         <div className="form-group">
            <label>Divider Text</label>
            <input type="text" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g., ---" />
        </div>
      )}

      {itemToEdit.type === 'Song' && (
        <>
          <div className="form-group"><label>Artist</label><input type="text" value={artist} onChange={(e) => setArtist(e.target.value)} /></div>
          <div className="form-group" style={{display:'grid', gridTemplateColumns:'1fr 1fr', gap:'1rem'}}>
              <div><label>Chord Chart</label><input type="url" value={chordChartUrl} onChange={(e) => setChordChartUrl(e.target.value)} /></div>
              <div><label>YouTube</label><input type="url" value={youtubeUrl} onChange={(e) => setYoutubeUrl(e.target.value)} /></div>
          </div>
          <div className="form-group">
            <label>Assign Singers</label>
            <div className="checkbox-group">
              {(assignedPeopleForSingerRole?.length > 0) ? assignedPeopleForSingerRole.map(p => (
                  <label key={p.id} className="checkbox-label">
                    <input type="checkbox" value={p.id} checked={selectedSingerIds.includes(p.id)} onChange={() => handleSingerSelectionChange(p.id)} />
                    {p.name}
                  </label>
                )) : <span style={{fontStyle:'italic', color:'#94a3b8'}}>No vocalists available.</span>}
            </div>
          </div>
        </>
      )}

      {itemToEdit.type === 'Bible Verse' && (
         <div className="form-group" style={{display:'grid', gridTemplateColumns:'1fr 1fr 1fr', gap:'0.5rem'}}>
            <div><label>Book</label><input type="text" value={bibleBook} onChange={(e) => setBibleBook(e.target.value)} required /></div>
            <div><label>Chapter</label><input type="text" value={bibleChapter} onChange={(e) => setBibleChapter(e.target.value)} required /></div>
            <div><label>Verse(s)</label><input type="text" value={bibleVerseRange} onChange={(e) => setBibleVerseRange(e.target.value)} required /></div>
        </div>
      )}

      {showDurationAndDetails && (
        <>
          <div className="form-group"><label>Duration</label><input type="text" value={duration} onChange={(e) => setDuration(e.target.value)} /></div>
          <div className="form-group"><label>Details</label><textarea value={details} onChange={(e) => setDetails(e.target.value)} /></div>
        </>
      )}

      <div className="form-actions">
        {itemToEdit.type === 'Song' && (
            <button type="button" className="cancel-btn" onClick={handleStartImport} style={{marginRight:'auto'}}>Import</button>
        )}
        <button type="button" className="cancel-btn" onClick={onCancel}>Cancel</button>
        <button type="submit" className="submit-btn" disabled={isSubmitting}>Save</button>
      </div>
    </form>
  );
};
export default EditServiceItemForm;